language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_STATIC_ANALYSIS=0
    - TASK_TESTS_COVERAGE=0

matrix:
  include:
    - php: "7.4"
      env:
        - TASK_STATIC_ANALYSIS=0 # set to 1 to enable static analysis
        - TASK_TESTS_COVERAGE=1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      pecl install ast
    fi

before_script:
  - php --version
  - composer --version
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
        PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
    fi

script:
  - phpdbg -qrr vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      composer phan
    fi
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      cat analysis.txt
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi


notifications:
  slack:
    -
      rooms:
        -
          secure: MRwDXagP6uwrx1C34wVEakwfbfJQMOPJi8PZarLzIYKkHZHHeNXX/eRVto7fkHsJh1M/UHh1raaEb8Y6EHF3hMY9yk3AZd6CK1t10oYe23m74j3srsXjhzVHXKgPhchcYEAI1/ITYn+u5Dpm/Bl8XC1kaiNgFYlDgM6O9n/xEWgfYs3fqtpl0kwFuO3CIq+6ahzD7Pq99gKzJSHKgjlSDJTBG9cxMfkUuctlO3AsSmagMlGtReGqCNOXvTPsEYpGWkUD2BNo4QlKMumjtLsA33mNss9ZNCDGCsqboC6rGhqDJyHVriUzrJ5793wWpeloRjy3VGaBIhW3oqGzjpftENcfG62mI7WU0iSVXlXdB63AFii0xRD//QcXGrPn2/GNDZoaITNunPX681nyK4yN4huCBqhGhum0mzO4/5zythGE15EBrgQ6YBpyCPw+bE/iKm5i5DFuW+rFxLtZ8IN4p77xavcZX5e7dZP9hnepHXmcKtfkMJQRFPsKXsOXU69RPwMpPVf1kLJv+MmrGIa9xo72A87w6GlRYfM7C0jaHulWzF1mLbtQHORM4Hdp43ZenPSns3M9vkIgOMfBO5JKq70YRI9KaEBZywERPmL/+R0eSw3ESZ6zAs4ldCHjuGyOSHCnS+Nuov/BdXnCcWLdflxW7wFfld5YK5bJIy1AauA=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: B0Vr3YSWwoHjFoPUahV6wPv6zDIueZq5caG+wgSN/DgWZQlZTtLYynp7U0YHTW1/7qL2Y/OcyxWG9pcpAiq69iAjxAwyJW486zs2Ei/628mDeK/PrnQ8hgQf+Vm9idElt+7EGn6fQzkQydm8MUHj2vQgZ43tVrLJBxe8v7NYoD1+h91pMVnnqCHREmDe7nEKXIJlcB1f4eh6uuNs7Lc3idxavJIXAcupBHP6RVTfpDsSzXuN4x/89JbmgjlANxDiwZCrQ7/bMI8ZfDQLzbn5KOlkxi0jprnENRGR5uckynQMuLbvqw93jBgighaD+n6X1OAZbeXH8i9uPlBW+/5odXm4rBy9wW1eHN4KmkiF1u2qPf20C4Cxj05gOVnmtpFitZf+dFoqpp1gmIVWlW1nF2a/g6v7jY2LMVd0MPYnw5W8ujeWj1PQZP97kM0YFfE91ZKlfBAEISoeXvbHwtTx/q3VxTc7EBAAm3DCNJftGfTcHZRjrM3dMAAnCfiHnp92Pm0Ijidv0+n5eBRyWkroH+lJNiKXdAMcMcY+2ZkaNCZE1fWO2u4eDaGv72IqG5cCx1TbyTd1y9VzryoOI6fMgQrMHaRWV1toIuHZYLD1ze282tk00Xc7I894wA5DBJHWkdbyQMkNb6cxe2xqiGAQGPdAFAel4FfUPWGkZUFF5Hg=
      on_success: never
      on_failure: always
      on_pull_requests: false
